In [3]:
import pandas as pd

# Read a .csv from a URL with Pandas
Target website: https://www.football-data.co.uk/data.php

In [4]:
# reading csv file from the url
df_p24 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [5]:
df_p24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

https://www.football-data.co.uk/mmz4281/2425/E0.csv

In [6]:
# link structure 
"https://www.football-data.co.uk/mmz4281/" + "2425" + "/"+"E0"+".csv"

'https://www.football-data.co.uk/mmz4281/2425/E0.csv'

In [7]:
root = "https://www.football-data.co.uk/mmz4281/"

In [8]:
leagues = ['E0','E1','E2','Ec']
frames = []
for league in leagues:
    df = pd.read_csv(root + '2425' + '/' + league + '.csv') # if encoding error comes put encoding = 'unicode_escape'
    frames.append(df)

In [9]:
frames

[    Div        Date   Time       HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    E0  16/08/2024  20:00     Man United       Fulham     1     0   H     0
 1    E0  17/08/2024  12:30        Ipswich    Liverpool     0     2   A     0
 2    E0  17/08/2024  15:00        Arsenal       Wolves     2     0   H     1
 3    E0  17/08/2024  15:00        Everton     Brighton     0     3   A     0
 4    E0  17/08/2024  15:00      Newcastle  Southampton     1     0   H     1
 ..   ..         ...    ...            ...          ...   ...   ...  ..   ...
 375  E0  25/05/2025  16:00      Newcastle      Everton     0     1   A     0
 376  E0  25/05/2025  16:00  Nott'm Forest      Chelsea     0     1   A     0
 377  E0  25/05/2025  16:00    Southampton      Arsenal     1     2   A     0
 378  E0  25/05/2025  16:00      Tottenham     Brighton     1     4   A     1
 379  E0  25/05/2025  16:00         Wolves    Brentford     1     1   D     0

      HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
 0       0  ...     1.86     2.07   1.83   2.11     1.88     2.11     1.82
 1       0  ...     2.05     1.88   2.04   1.90     2.20     2.00     1.99
 2       0  ...     2.02     1.91   2.00   1.90     2.05     1.93     1.99
 3       1  ...     1.87     2.06   1.86   2.07     1.92     2.10     1.83
 4       0  ...     1.87     2.06   1.88   2.06     1.89     2.10     1.82
 ..    ...  ...      ...      ...    ...    ...      ...      ...      ...
 375     0  ...     2.00     1.85   2.01   1.90     2.01     1.95     1.95
 376     0  ...     1.80     2.05   1.86   2.08     1.86     2.08     1.81
 377     1  ...     2.03     1.83   2.04   1.87     2.07     1.87     2.03
 378     0  ...     1.95     1.90   2.00   1.93     2.01     1.93     1.95
 379     1  ...     1.85     2.00   1.90   2.03     1.90     2.05     1.85

      AvgCAHA  BFECAHH  BFECAHA
 0       2.05     1.90     2.08
 1       1.88     2.04     1.93
 2       1.87     2.02     1.96
 3       2.04     1.88     2.11
 4       2.05     1.89     2.10
 ..       ...      ...      ...
 375     1.91     1.93     2.05
 376     2.05     1.86     2.14
 377     1.83     2.06     1.89
 378     1.89     2.06     1.93
 379     1.97     1.89     2.10

 [380 rows x 120 columns],
     Div        Date   Time          HomeTeam          AwayTeam  FTHG  FTAG  \
 0    E1  09/08/2024  20:00         Blackburn             Derby     4     2
 1    E1  09/08/2024  20:00           Preston  Sheffield United     0     2
 2    E1  10/08/2024  12:30           Cardiff        Sunderland     0     2
 3    E1  10/08/2024  12:30              Hull      Bristol City     1     1
 4    E1  10/08/2024  12:30             Leeds        Portsmouth     3     3
 ..   ..         ...    ...               ...               ...   ...   ...
 547  E1  03/05/2025  12:30  Sheffield United         Blackburn     1     1
 548  E1  03/05/2025  12:30        Sunderland               QPR     0     1
 549  E1  03/05/2025  12:30           Swansea            Oxford     3     3
 550  E1  03/05/2025  12:30           Watford    Sheffield Weds     1     1
 551  E1  03/05/2025  12:30         West Brom             Luton     5     3

     FTR  HTHG  HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  \
 0     H     1     0  ...     1.85     2.05   1.85   2.06     1.97     2.10
 1     A     0     1  ...     1.92     1.98   1.93   1.98     1.97     1.99
 2     A     0     1  ...     2.11     1.79   2.13   1.80     2.13     1.81
 3     D     0     0  ...     1.99     1.91   2.00   1.91     2.04     1.91
 4     D     1     2  ...     1.92     1.98   1.93   1.95     2.00     1.98
 ..   ..   ...   ...  ...      ...      ...    ...    ...      ...      ...
 547   D     0     0  ...     1.89     2.01   1.90   2.01     1.91     2.11
 548   A     0     1  ...     2.01     1.89   2.04   1.88     2.19     1.89
 549   D     1     1  ...     2.02     1.88   2.03   1.88     2.08     1.89
 550   D     1     1  ...     1.85     2.00   1.86   2.05     2.00     2.05
 551   H     3     1  ...     1.91     1.99   1.89   2.01     1.97     2.01

      AvgCAHH  AvgCAHA  BFECAHH  BFECAHA
 0       1.85     1.99     1.88     2.11
 1       1.90     1.94     1.94     2.04
 2       2.09     1.79     2.18     1.83
 3       1.99     1.87     2.03     1.96
 4       1.94     1.89     2.00     1.97
 ..       ...      ...      ...      ...
 547     1.84     2.04     1.89     2.10
 548     2.04     1.81     2.16     1.82
 549     2.00     1.85     2.09     1.89
 550     1.92     1.94     2.00     1.99
 551     1.87     1.94     1.92     2.05

 [552 rows x 120 columns],
     Div        Date   Time      HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    E2  09/08/2024  20:00      Barnsley     Mansfield     1     2   A     1
 1    E2  10/08/2024  17:30    Birmingham       Reading     1     1   D     0
 2    E2  10/08/2024  17:30   Bristol Rvs   Northampton     1     0   H     0
 3    E2  10/08/2024  17:30        Burton       Lincoln     2     3   A     2
 4    E2  10/08/2024  17:30  Crawley Town     Blackpool     2     1   H     2
 ..   ..         ...    ...           ...           ...   ...   ...  ..   ...
 547  E2  03/05/2025  15:00   Northampton         Wigan     1     1   D     1
 548  E2  03/05/2025  15:00       Reading      Barnsley     2     4   A     0
 549  E2  03/05/2025  15:00     Rotherham     Peterboro     2     1   H     1
 550  E2  03/05/2025  15:00    Shrewsbury  Crawley Town     1     2   A     0
 551  E2  03/05/2025  15:00       Wycombe     Stockport     1     3   A     1

      HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
 0       2  ...     2.03     1.83   2.02   1.87     2.05     2.00     1.95
 1       1  ...     1.80     2.05   1.81   2.10     1.83     2.10     1.80
 2       0  ...     1.98     1.88   1.98   1.91     1.98     1.92     1.93
 3       2  ...     1.80     2.05   1.82   2.08     1.88     2.09     1.80
 4       0  ...     1.83     2.03   1.85   2.04     1.86     2.05     1.82
 ..    ...  ...      ...      ...    ...    ...      ...      ...      ...
 547     0  ...     2.05     1.80   2.09   1.78     2.11     1.80     2.03
 548     0  ...     1.85     2.00   1.79   2.07     1.85     2.12     1.79
 549     1  ...     1.93     1.93   1.93   1.92     2.00     1.95     1.91
 550     0  ...     2.03     1.83   2.05   1.81     2.10     1.83     2.03
 551     0  ...     1.85     2.00   1.87   1.99     1.87     2.15     1.80

      AvgCAHA  BFECAHH  BFECAHA
 0       1.85     2.06     1.93
 1       2.01     1.82     2.16
 2       1.86     2.02     1.97
 3       2.01     1.88     2.11
 4       1.99     1.89     2.08
 ..       ...      ...      ...
 547     1.78     2.13     1.84
 548     2.03     1.87     2.11
 549     1.89     1.98     2.00
 550     1.79     2.11     1.87
 551     2.04     1.88     2.11

 [552 rows x 120 columns],
     Div        Date   Time     HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    EC  10/08/2024  15:00    Aldershot  Forest Green     3     3   D     2
 1    EC  10/08/2024  15:00   Altrincham        Woking     1     0   H     1
 2    EC  10/08/2024  15:00   Boston Utd      Rochdale     0     3   A     0
 3    EC  10/08/2024  15:00  Dag and Red    Wealdstone     2     1   H     0
 4    EC  10/08/2024  15:00        Fylde      Solihull     3     2   H     1
 ..   ..         ...    ...          ...           ...   ...   ...  ..   ...
 547  EC  05/05/2025  15:00   Maidenhead    Boston Utd     3     0   H     1
 548  EC  05/05/2025  15:00       Oldham     Ebbsfleet     2     0   H     1
 549  EC  05/05/2025  15:00     Solihull   Dag and Red     1     1   D     0
 550  EC  05/05/2025  15:00       Sutton        Woking     1     1   D     0
 551  EC  05/05/2025  15:00   Wealdstone       Halifax     3     1   H     3

      HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
 0       1  ...     1.83     1.98   1.87   1.99     1.87     2.00     1.83
 1       0  ...     1.83     1.98   1.83   2.04     1.85     2.04     1.82
 2       2  ...     1.85     1.95   1.88   1.98     1.88     1.98     1.84
 3       0  ...     1.90     1.90   1.89   1.95     1.91     1.95     1.87
 4       2  ...     1.78     2.03   1.76   2.10     1.80     2.10     1.76
 ..    ...  ...      ...      ...    ...    ...      ...      ...      ...
 547     0  ...     1.80     2.00   1.80   2.07     1.81     2.07     1.77
 548     0  ...     1.85     1.95   1.88   1.98     1.90     1.98     1.87
 549     1  ...     1.98     1.83   1.96   1.89     1.98     1.89     1.95
 550     1  ...     1.95     1.85   1.93   1.93     1.95     1.93     1.93
 551     0  ...     2.03     1.78   2.07   1.80     2.07     1.81     2.01

      AvgCAHA  BFECAHH  BFECAHA
 0       1.99     1.88     2.02
 1       1.95     1.86     2.14
 2       1.93     1.92     2.00
 3       1.88     1.91     2.06
 4       2.01     1.80     2.14
 ..       ...      ...      ...
 547     2.02     1.83     2.13
 548     1.91     1.94     1.90
 549     1.84     2.02     1.91
 550     1.84     2.01     1.96
 551     1.78     2.12     1.72

 [552 rows x 112 columns]]

In [10]:
frames[0] # E0

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

# multiple seasons

In [11]:
leagues = ['E0','E2','E3']
frames = []

for league in leagues:
    for season in range(15,21):
        df = pd.read_csv(root + (str(season) + str(season+1)) + '/' + league + '.csv',encoding = 'unicode_escape') # if encoding error comes put encoding = 'unicode_escape'
        df.insert(1,'season',season)
        frames.append(df)

In [12]:
frames

[    Div  season        Date     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
 0    E0      15  08/08/2015  Bournemouth  Aston Villa     0     1   A     0
 1    E0      15  08/08/2015      Chelsea      Swansea     2     2   D     2
 2    E0      15  08/08/2015      Everton      Watford     2     2   D     0
 3    E0      15  08/08/2015    Leicester   Sunderland     4     2   H     3
 4    E0      15  08/08/2015   Man United    Tottenham     1     0   H     1
 ..   ..     ...         ...          ...          ...   ...   ...  ..   ...
 375  E0      15  15/05/2016        Stoke     West Ham     2     1   H     0
 376  E0      15  15/05/2016      Swansea     Man City     1     1   D     1
 377  E0      15  15/05/2016      Watford   Sunderland     2     2   D     0
 378  E0      15  15/05/2016    West Brom    Liverpool     1     1   D     1
 379  E0      15  17/05/2016   Man United  Bournemouth     3     1   H     1

      HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  PSCH  \
 0       0  ...     1.79   26  -0.50     1.98     1.93     1.99     1.92  1.82
 1       1  ...     1.99   27  -1.50     2.24     2.16     1.80     1.73  1.37
 2       1  ...     1.96   26  -1.00     2.28     2.18     1.76     1.71  1.75
 3       0  ...     1.67   26  -0.50     2.00     1.95     1.96     1.90  1.79
 4       0  ...     2.01   26  -1.00     2.20     2.09     1.82     1.78  1.64
 ..    ...  ...      ...  ...    ...      ...      ...      ...      ...   ...
 375     1  ...     2.27   30   0.25     2.11     2.03     1.87     1.83  3.05
 376     1  ...     2.45   31   1.00     2.14     2.05     1.85     1.81  7.05
 377     1  ...     2.10   29  -0.50     2.06     2.01     1.91     1.85  1.64
 378     1  ...     2.09   30  -0.25     2.10     2.05     1.86     1.81  2.61
 379     0  ...     2.20   29  -0.75     1.88     1.84     2.08     2.02  1.50

      PSCD   PSCA
 0    3.88   4.70
 1    5.04  10.88
 2    3.76   5.44
 3    3.74   5.10
 4    4.07   6.04
 ..    ...    ...
 375  4.00   2.26
 376  5.00   1.47
 377  4.52   5.27
 378  3.75   2.70
 379  4.60   7.03

 [380 rows x 66 columns],
     Div  season      Date        HomeTeam        AwayTeam  FTHG  FTAG FTR  \
 0    E0      16  13/08/16         Burnley         Swansea     0     1   A
 1    E0      16  13/08/16  Crystal Palace       West Brom     0     1   A
 2    E0      16  13/08/16         Everton       Tottenham     1     1   D
 3    E0      16  13/08/16            Hull       Leicester     2     1   H
 4    E0      16  13/08/16        Man City      Sunderland     2     1   H
 ..   ..     ...       ...             ...             ...   ...   ...  ..
 375  E0      16  21/05/17       Liverpool   Middlesbrough     3     0   H
 376  E0      16  21/05/17      Man United  Crystal Palace     2     0   H
 377  E0      16  21/05/17     Southampton           Stoke     0     1   A
 378  E0      16  21/05/17         Swansea       West Brom     2     1   H
 379  E0      16  21/05/17         Watford        Man City     0     5   A

      HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
 0       0     0  ...     1.61   32  -0.25     2.13     2.06     1.86     1.81
 1       0     0  ...     1.52   33  -0.50     2.07     2.00     1.90     1.85
 2       1     0  ...     1.77   32   0.25     1.91     1.85     2.09     2.00
 3       1     0  ...     1.67   31   0.25     2.35     2.26     2.03     1.67
 4       1     0  ...     2.48   34  -1.50     1.81     1.73     2.20     2.14
 ..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
 375     1     0  ...     2.73   18  -2.50     2.02     1.97     1.95     1.90
 376     2     0  ...     1.81   19  -0.25     2.19     2.11     1.85     1.79
 377     0     0  ...     2.01   18  -0.75     2.03     1.98     1.93     1.88
 378     0     1  ...     1.98   19  -0.50     2.11     2.06     1.86     1.82
 379     0     4  ...     2.80   18   1.75     1.99     1.94     2.00     1.93

       PSCH   PSCD   PSCA
 0     2.79   3.16   2.89
 1     2.25   3.15   3.86
 2     3.64   3.54   2.16
 3     4.68   3.50   1.92
 4     1.25   6.50  14.50
 ..     ...    ...    ...
 375   1.15  10.50  19.09
 376   2.35   3.38   3.35
 377   1.64   4.37   5.53
 378   2.29   3.45   3.40
 379  18.00   9.70   1.16

 [380 rows x 66 columns],
     Div  season        Date        HomeTeam      AwayTeam  FTHG  FTAG FTR  \
 0    E0      17  11/08/2017         Arsenal     Leicester     4     3   H
 1    E0      17  12/08/2017        Brighton      Man City     0     2   A
 2    E0      17  12/08/2017         Chelsea       Burnley     2     3   A
 3    E0      17  12/08/2017  Crystal Palace  Huddersfield     0     3   A
 4    E0      17  12/08/2017         Everton         Stoke     1     0   H
 ..   ..     ...         ...             ...           ...   ...   ...  ..
 375  E0      17  13/05/2018       Newcastle       Chelsea     3     0   H
 376  E0      17  13/05/2018     Southampton      Man City     0     1   A
 377  E0      17  13/05/2018         Swansea         Stoke     1     2   A
 378  E0      17  13/05/2018       Tottenham     Leicester     5     4   H
 379  E0      17  13/05/2018        West Ham       Everton     3     1   H

      HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
 0       2     2  ...     2.32   21  -1.00     1.91     1.85     2.10     2.02
 1       0     0  ...     2.27   20   1.50     1.95     1.91     2.01     1.96
 2       0     3  ...     2.23   20  -1.75     2.03     1.97     1.95     1.90
 3       0     2  ...     1.72   18  -0.75     2.10     2.05     1.86     1.83
 4       1     0  ...     1.76   19  -0.75     1.94     1.90     2.01     1.98
 ..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
 375     1     0  ...     2.01   21   1.00     1.90     1.83     2.11     2.03
 376     0     0  ...     2.49   20   1.25     2.01     1.95     1.97     1.91
 377     1     2  ...     2.06   19  -0.50     1.94     1.88     2.03     1.98
 378     1     2  ...     2.84   20  -1.50     1.96     1.86     2.05     2.00
 379     1     0  ...     1.97   21  -0.25     2.09     2.03     1.88     1.84

       PSCH  PSCD   PSCA
 0     1.49  4.73   7.25
 1    11.75  6.15   1.29
 2     1.33  5.40  12.25
 3     1.79  3.56   5.51
 4     1.82  3.49   5.42
 ..     ...   ...    ...
 375   4.85  3.72   1.80
 376   6.32  4.78   1.51
 377   2.08  3.56   3.82
 378   1.38  5.50   8.15
 379   2.35  3.40   3.28

 [380 rows x 66 columns],
     Div  season        Date      HomeTeam        AwayTeam  FTHG  FTAG FTR  \
 0    E0      18  10/08/2018    Man United       Leicester     2     1   H
 1    E0      18  11/08/2018   Bournemouth         Cardiff     2     0   H
 2    E0      18  11/08/2018        Fulham  Crystal Palace     0     2   A
 3    E0      18  11/08/2018  Huddersfield         Chelsea     0     3   A
 4    E0      18  11/08/2018     Newcastle       Tottenham     1     2   A
 ..   ..     ...         ...           ...             ...   ...   ...  ..
 375  E0      18  12/05/2019     Liverpool          Wolves     2     0   H
 376  E0      18  12/05/2019    Man United         Cardiff     0     2   A
 377  E0      18  12/05/2019   Southampton    Huddersfield     1     1   D
 378  E0      18  12/05/2019     Tottenham         Everton     2     2   D
 379  E0      18  12/05/2019       Watford        West Ham     1     4   A

      HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
 0       1     0  ...     1.79   17  -0.75     1.75     1.70     2.29     2.21
 1       1     0  ...     1.83   20  -0.75     2.20     2.13     1.80     1.75
 2       0     1  ...     1.87   22  -0.25     2.18     2.11     1.81     1.77
 3       0     2  ...     1.84   23   1.00     1.84     1.80     2.13     2.06
 4       1     2  ...     1.81   20   0.25     2.20     2.12     1.80     1.76
 ..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
 375     1     0  ...     2.31   22  -1.50     1.98     1.91     2.01     1.95
 376     0     1  ...     2.95   21  -2.00     2.52     2.32     1.72     1.64
 377     1     0  ...     2.29   22  -1.50     2.27     2.16     1.80     1.73
 378     1     0  ...     2.07   19  -0.50     2.13     2.08     1.85     1.80
 379     0     2  ...     2.44   19  -0.50     2.25     2.19     1.78     1.72

      PSCH  PSCD  PSCA
 0    1.55  4.07  7.69
 1    1.88  3.61  4.70
 2    2.62  3.38  2.90
 3    7.24  3.95  1.58
 4    4.74  3.53  1.89
 ..    ...   ...   ...
 375  1.32  5.89  9.48
 376  1.30  6.06  9.71
 377  1.37  5.36  8.49
 378  1.91  3.81  4.15
 379  2.11  3.86  3.41

 [380 rows x 63 columns],
     Div  season        Date   Time        HomeTeam          AwayTeam  FTHG  \
 0    E0      19  09/08/2019  20:00       Liverpool           Norwich     4
 1    E0      19  10/08/2019  12:30        West Ham          Man City     0
 2    E0      19  10/08/2019  15:00     Bournemouth  Sheffield United     1
 3    E0      19  10/08/2019  15:00         Burnley       Southampton     3
 4    E0      19  10/08/2019  15:00  Crystal Palace           Everton     0
 ..   ..     ...         ...    ...             ...               ...   ...
 375  E0      19  26/07/2020  16:00       Leicester        Man United     0
 376  E0      19  26/07/2020  16:00        Man City           Norwich     5
 377  E0      19  26/07/2020  16:00       Newcastle         Liverpool     1
 378  E0      19  26/07/2020  16:00     Southampton  Sheffield United     3
 379  E0      19  26/07/2020  16:00        West Ham       Aston Villa     1

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       1   H     4  ...      3.43 -2.25     1.91      1.99   1.94   1.98
 1       5   A     0  ...      2.91  1.75     1.95      1.95   1.96   1.97
 2       1   D     0  ...      1.92 -0.50     1.95      1.95   1.98   1.95
 3       0   H     0  ...      1.71  0.00     1.87      2.03   1.89   2.03
 4       0   D     0  ...      1.71  0.25     1.82      2.08   1.97   1.96
 ..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
 375     2   A     0  ...      2.03  0.50     1.89      2.01   1.88   2.05
 376     0   H     2  ...      5.77 -3.75     2.03      1.87   2.01   1.88
 377     3   A     1  ...      2.40  1.00     1.94      1.96   1.95   1.97
 378     1   H     0  ...      2.01 -0.50     1.97      1.93   2.00   1.93
 379     1   D     0  ...      2.03  0.00     1.93      1.97   1.95   1.98

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       1.99     2.07     1.90     1.99
 1       2.07     1.98     1.97     1.92
 2       2.00     1.96     1.96     1.92
 3       1.90     2.07     1.86     2.02
 4       2.03     2.08     1.96     1.93
 ..       ...      ...      ...      ...
 375     1.94     2.05     1.86     2.02
 376     2.06     1.88     2.02     1.84
 377     2.03     2.00     1.95     1.92
 378     2.03     1.96     1.98     1.89
 379     1.99     2.00     1.93     1.95

 [380 rows x 107 columns],
     Div  season        Date   Time          HomeTeam        AwayTeam  FTHG  \
 0    E0      20  12/09/2020  12:30            Fulham         Arsenal     0
 1    E0      20  12/09/2020  15:00    Crystal Palace     Southampton     1
 2    E0      20  12/09/2020  17:30         Liverpool           Leeds     4
 3    E0      20  12/09/2020  20:00          West Ham       Newcastle     0
 4    E0      20  13/09/2020  14:00         West Brom       Leicester     0
 ..   ..     ...         ...    ...               ...             ...   ...
 375  E0      20  23/05/2021  16:00         Liverpool  Crystal Palace     2
 376  E0      20  23/05/2021  16:00          Man City         Everton     5
 377  E0      20  23/05/2021  16:00  Sheffield United         Burnley     1
 378  E0      20  23/05/2021  16:00          West Ham     Southampton     3
 379  E0      20  23/05/2021  16:00            Wolves      Man United     1

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       3   A     0  ...      1.84  0.75     2.01      1.89   2.02   1.91
 1       0   H     1  ...      1.70  0.25     1.78      2.13   1.79   2.17
 2       3   H     3  ...      2.62 -1.50     1.85      2.05   1.85   2.08
 3       2   A     0  ...      1.92 -0.50     2.03      1.87   2.04   1.88
 4       3   A     0  ...      1.73  0.25     1.92      1.98   1.93   1.99
 ..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
 375     0   H     1  ...      3.49 -2.25     1.86      2.04   1.88   2.03
 376     0   H     2  ...      2.77 -1.75     2.01      1.89   1.99   1.89
 377     0   H     1  ...      2.05  0.00     2.04      1.86   2.05   1.86
 378     0   H     2  ...      2.14 -0.75     2.00      1.90   2.02   1.91
 379     2   A     1  ...      1.62 -0.25     2.04      1.86   2.10   1.84

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       2.13     1.92     2.02     1.87
 1       1.85     2.18     1.79     2.12
 2       1.90     2.16     1.84     2.04
 3       2.09     1.91     2.02     1.86
 4       1.95     2.01     1.91     1.97
 ..       ...      ...      ...      ...
 375     1.98     2.14     1.88     2.00
 376     2.20     2.00     2.03     1.85
 377     2.17     1.90     2.03     1.84
 378     2.06     2.01     1.99     1.89
 379     2.10     1.94     2.00     1.88

 [380 rows x 107 columns],
      Div  season      Date          HomeTeam    AwayTeam  FTHG  FTAG  FTR  \
 0     E2      15  08/08/15            Burton  Scunthorpe   2.0   1.0    H
 1     E2      15  08/08/15      Chesterfield    Barnsley   3.0   1.0    H
 2     E2      15  08/08/15        Colchester   Blackpool   2.0   2.0    D
 3     E2      15  08/08/15          Coventry       Wigan   2.0   0.0    H
 4     E2      15  08/08/15             Crewe   Port Vale   0.0   0.0    D
 ..   ...     ...       ...               ...         ...   ...   ...  ...
 548   E2      15  08/05/16         Port Vale     Walsall   0.0   5.0    A
 549   E2      15  08/05/16  Sheffield United  Scunthorpe   0.0   2.0    A
 550   E2      15  08/05/16           Swindon  Shrewsbury   3.0   0.0    H
 551   E2      15  08/05/16             Wigan    Barnsley   1.0   4.0    A
 552  NaN      15       NaN               NaN         NaN   NaN   NaN  NaN

      HTHG  HTAG  ... BbAv<2.5  BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  \
 0     0.0   0.0  ...     1.74  25.0  -0.25     1.99     1.93     1.94
 1     0.0   1.0  ...     1.75  25.0  -0.25     1.93     1.87     2.02
 2     1.0   2.0  ...     1.77  25.0  -0.25     1.94     1.88     2.01
 3     1.0   0.0  ...     1.64  25.0   0.25     1.85     1.78     2.12
 4     0.0   0.0  ...     1.75  23.0  -0.25     2.22     2.13     1.76
 ..    ...   ...  ...      ...   ...    ...      ...      ...      ...
 548   0.0   3.0  ...     1.96  26.0   0.75     1.74     1.69     2.29
 549   0.0   1.0  ...     2.06  27.0   0.25     1.93     1.86     2.02
 550   1.0   0.0  ...     2.22  27.0  -0.25     2.00     1.93     1.96
 551   1.0   2.0  ...     2.00  27.0  -0.25     2.08     2.01     1.87
 552   NaN   NaN  ...      NaN   NaN    NaN      NaN      NaN      NaN

      BbAvAHA  PSCH  PSCD  PSCA
 0       1.88  2.40  3.38  3.19
 1       1.94  2.02  3.60  3.96
 2       1.93  2.28  3.51  3.31
 3       2.05  2.92  3.31  2.63
 4       1.72  3.05  3.51  2.43
 ..       ...   ...   ...   ...
 548     2.19  4.19  3.94  1.88
 549     1.96  3.17  3.80  2.24
 550     1.89  2.21  3.68  3.32
 551     1.82  2.32  3.85  2.99
 552      NaN   NaN   NaN   NaN

 [553 rows x 66 columns],
     Div  season      Date          HomeTeam            AwayTeam  FTHG  FTAG  \
 0    E2      16  06/08/16            Bolton    Sheffield United     1     0
 1    E2      16  06/08/16          Bradford           Port Vale     0     0
 2    E2      16  06/08/16              Bury            Charlton     2     0
 3    E2      16  06/08/16          Millwall              Oldham     3     0
 4    E2      16  06/08/16       Northampton      Fleetwood Town     1     1
 ..   ..     ...       ...               ...                 ...   ...   ...
 547  E2      16  30/04/17          Rochdale            Bradford     1     1
 548  E2      16  30/04/17        Scunthorpe            Coventry     3     1
 549  E2      16  30/04/17  Sheffield United        Chesterfield     3     2
 550  E2      16  30/04/17          Southend                Bury     1     0
 551  E2      16  30/04/17           Walsall  Milton Keynes Dons     1     4

     FTR  HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  \
 0     H     1     0  ...     1.68   28   0.00     2.08     2.00     1.87
 1     D     0     0  ...     1.68   29  -0.75     1.97     1.91     1.96
 2     H     0     0  ...     1.74   29   0.25     1.80     1.74     2.20
 3     H     2     0  ...     1.80   29  -0.75     1.85     1.80     2.10
 4     D     1     0  ...     1.67   29  -0.25     2.00     1.91     1.99
 ..   ..   ...   ...  ...      ...  ...    ...      ...      ...      ...
 547   D     0     1  ...     2.08   20  -0.25     2.00     1.94     1.95
 548   H     0     1  ...     1.93   18  -1.00     2.13     2.02     1.86
 549   H     1     1  ...     2.94   18  -2.00     1.95     1.88     2.01
 550   H     1     0  ...     2.03   18  -0.75     2.01     1.96     1.95
 551   A     0     2  ...     1.90   16   0.00     2.10     2.06     1.84

      BbAvAHA  PSCH  PSCD   PSCA
 0       1.81  3.20  3.35   2.41
 1       1.91  1.78  3.59   5.45
 2       2.11  2.73  3.41   2.73
 3       2.03  1.55  4.22   7.05
 4       1.91  2.28  3.37   3.46
 ..       ...   ...   ...    ...
 547     1.90  1.81  3.85   4.70
 548     1.81  1.64  4.29   5.52
 549     1.95  1.20  7.90  15.00
 550     1.88  1.78  3.89   4.86
 551     1.81  3.21  3.66   2.27

 [552 rows x 66 columns],
     Div  season      Date        HomeTeam            AwayTeam  FTHG  FTAG FTR  \
 0    E2      17  05/08/17        Bradford           Blackpool     2     1   H
 1    E2      17  05/08/17            Bury             Walsall     1     0   H
 2    E2      17  05/08/17        Charlton         Bristol Rvs     1     0   H
 3    E2      17  05/08/17       Doncaster          Gillingham     0     0   D
 4    E2      17  05/08/17  Fleetwood Town           Rotherham     2     0   H
 ..   ..     ...       ...             ...                 ...   ...   ...  ..
 547  E2      17  05/05/18        Rochdale            Charlton     1     0   H
 548  E2      17  05/05/18       Rotherham           Blackpool     1     0   H
 549  E2      17  05/05/18      Scunthorpe            Bradford     1     1   D
 550  E2      17  05/05/18      Shrewsbury  Milton Keynes Dons     0     1   A
 551  E2      17  05/05/18        Southend         Bristol Rvs     0     0   D

      HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
 0       1     1  ...     1.64   16  -0.75     1.86     1.81     2.08     2.04
 1       1     0  ...     1.79   16  -0.50     2.09     2.03     1.87     1.82
 2       1     0  ...     1.89   16  -0.25     2.07     2.02     1.89     1.83
 3       0     0  ...     1.88   16  -0.50     1.83     1.79     2.11     2.06
 4       1     0  ...     1.75   16  -0.25     2.00     1.94     1.98     1.91
 ..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
 547     0     0  ...     1.73   18  -0.25     1.86     1.81     2.06     2.01
 548     0     0  ...     1.91   18  -0.25     2.20     2.11     1.80     1.74
 549     0     0  ...     1.81   18  -0.50     1.93     1.86     2.01     1.96
 550     0     0  ...     1.77   17  -0.75     2.12     2.03     1.84     1.80
 551     0     0  ...     1.98   19  -0.25     2.03     1.95     1.95     1.87

      PSCH  PSCD  PSCA
 0    1.69  3.97  5.50
 1    2.02  3.55  4.03
 2    2.19  3.66  3.39
 3    1.69  3.96  5.45
 4    2.20  3.38  3.66
 ..    ...   ...   ...
 547  1.92  3.89  3.98
 548  2.14  3.79  3.34
 549  1.92  3.68  4.21
 550  1.76  3.84  4.98
 551  2.23  3.78  3.16

 [552 rows x 66 columns],

In [13]:
len(frames)

18

In [14]:
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

# Organize All The Data in a Dictionary

In [15]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [21]:
dict_historical_data = {} 
frames = []

for league in dict_countries:
    frames = []
    for season in range(15,21):
        df = pd.read_csv(root + (str(season) + str(season+1)) + '/' + dict_countries[league] + '.csv',encoding = 'unicode_escape') # if encoding error comes put encoding = 'unicode_escape'
        df.insert(1,'season',season)
        df.insert(1,'league_name',league)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [22]:
dict_historical_data

{'Spanish La Liga':      Div      league_name  season        Date     HomeTeam    AwayTeam  FTHG  \
 0    SP1  Spanish La Liga      15    21/08/15       Malaga     Sevilla     0
 1    SP1  Spanish La Liga      15    22/08/15   Ath Madrid  Las Palmas     1
 2    SP1  Spanish La Liga      15    22/08/15      Espanol      Getafe     1
 3    SP1  Spanish La Liga      15    22/08/15    La Coruna    Sociedad     0
 4    SP1  Spanish La Liga      15    22/08/15    Vallecano    Valencia     0
 ..   ...              ...     ...         ...          ...         ...   ...
 375  SP1  Spanish La Liga      20  22/05/2021      Osasuna    Sociedad     0
 376  SP1  Spanish La Liga      20  22/05/2021  Real Madrid  Villarreal     2
 377  SP1  Spanish La Liga      20  22/05/2021   Valladolid  Ath Madrid     1
 378  SP1  Spanish La Liga      20  23/05/2021      Granada      Getafe     0
 379  SP1  Spanish La Liga      20  23/05/2021      Sevilla      Alaves     1

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       0   D     0  ...       NaN   NaN       NaN       NaN    NaN    NaN
 1       0   H     1  ...       NaN   NaN       NaN       NaN    NaN    NaN
 2       0   H     1  ...       NaN   NaN       NaN       NaN    NaN    NaN
 3       0   D     0  ...       NaN   NaN       NaN       NaN    NaN    NaN
 4       0   D     0  ...       NaN   NaN       NaN       NaN    NaN    NaN
 ..    ...  ..   ...  ...       ...   ...       ...       ...    ...    ...
 375     1   A     0  ...      2.34  1.00      2.07      1.86   2.06   1.87
 376     1   H     0  ...      2.57 -1.00      2.01      1.92   2.00   1.93
 377     2   A     1  ...      2.30  1.50      1.90      2.03   1.90   2.02
 378     0   D     0  ...      1.80  0.25      1.73      2.08   1.77   2.18
 379     0   H     0  ...      2.40 -1.50      1.97      1.96   1.93   1.99

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN      NaN      NaN
 1        NaN      NaN      NaN      NaN
 2        NaN      NaN      NaN      NaN
 3        NaN      NaN      NaN      NaN
 4        NaN      NaN      NaN      NaN
 ..       ...      ...      ...      ...
 375     2.07     1.96     1.98     1.88
 376     2.02     2.02     1.95     1.92
 377     1.95     2.06     1.90     1.97
 378     1.84     2.23     1.77     2.12
 379     2.13     2.03     1.99     1.88

 [2280 rows x 128 columns],
 'Spanish Segunda Division':      Div               league_name  season        Date      HomeTeam  \
 0    SP2  Spanish Segunda Division      15    22/08/15      Alcorcon
 1    SP2  Spanish Segunda Division      15    22/08/15       Cordoba
 2    SP2  Spanish Segunda Division      15    22/08/15        Huesca
 3    SP2  Spanish Segunda Division      15    22/08/15    Llagostera
 4    SP2  Spanish Segunda Division      15    23/08/15       Almeria
 ..   ...                       ...     ...         ...           ...
 457  SP2  Spanish Segunda Division      20  30/05/2021      Mirandes
 458  SP2  Spanish Segunda Division      20  30/05/2021  Ponferradina
 459  SP2  Spanish Segunda Division      20  30/05/2021      Sp Gijon
 460  SP2  Spanish Segunda Division      20  30/05/2021     Vallecano
 461  SP2  Spanish Segunda Division      20  30/05/2021      Zaragoza

        AwayTeam  FTHG  FTAG FTR  HTHG  ...  AvgC<2.5  AHCh  B365CAHH  \
 0      Mallorca     2     0   H   1.0  ...       NaN   NaN       NaN
 1    Valladolid     1     0   H   0.0  ...       NaN   NaN       NaN
 2        Alaves     2     3   A   0.0  ...       NaN   NaN       NaN
 3       Osasuna     0     2   A   0.0  ...       NaN   NaN       NaN
 4       Leganes     3     2   H   3.0  ...       NaN   NaN       NaN
 ..          ...   ...   ...  ..   ...  ...       ...   ...       ...
 457    Sabadell     0     2   A   0.0  ...      1.74  0.50      2.02
 458    Mallorca     2     2   D   1.0  ...      1.83  0.25      2.00
 459     Almeria     0     2   A   0.0  ...      1.83 -0.75      1.80
 460        Lugo     0     1   A   0.0  ...      1.87 -1.00      1.95
 461     Leganes     0     5   A   0.0  ...      1.64  0.50      1.83

      B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 1         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 2         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 3         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 4         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 ..        ...    ...    ...      ...      ...      ...      ...
 457      1.83   2.05   1.86     2.06     1.89     2.00     1.83
 458      1.85   2.02   1.89     2.04     1.92     1.99     1.85
 459      2.05   1.84   2.08     1.89     2.08     1.83     2.02
 460      1.90   1.97   1.93     2.02     1.94     1.96     1.88
 461      2.02   1.85   2.07     1.87     2.08     1.80     2.04

 [2772 rows x 128 columns],
 'German Bundesliga':     Div        league_name  season        Date       HomeTeam    AwayTeam  \
 0    D1  German Bundesliga      15    14/08/15  Bayern Munich     Hamburg
 1    D1  German Bundesliga      15    15/08/15       Augsburg      Hertha
 2    D1  German Bundesliga      15    15/08/15      Darmstadt    Hannover
 3    D1  German Bundesliga      15    15/08/15       Dortmund  M'gladbach
 4    D1  German Bundesliga      15    15/08/15     Leverkusen  Hoffenheim
 ..   ..                ...     ...         ...            ...         ...
 301  D1  German Bundesliga      20  22/05/2021     Hoffenheim      Hertha
 302  D1  German Bundesliga      20  22/05/2021      Stuttgart   Bielefeld
 303  D1  German Bundesliga      20  22/05/2021   Union Berlin  RB Leipzig
 304  D1  German Bundesliga      20  22/05/2021  Werder Bremen  M'gladbach
 305  D1  German Bundesliga      20  22/05/2021      Wolfsburg       Mainz

      FTHG  FTAG FTR  HTHG  ...  AvgC<2.5  AHCh  B365CAHH  B365CAHA  PCAHH  \
 0       5     0   H     1  ...       NaN   NaN       NaN       NaN    NaN
 1       0     1   A     0  ...       NaN   NaN       NaN       NaN    NaN
 2       2     2   D     1  ...       NaN   NaN       NaN       NaN    NaN
 3       4     0   H     3  ...       NaN   NaN       NaN       NaN    NaN
 4       2     1   H     1  ...       NaN   NaN       NaN       NaN    NaN
 ..    ...   ...  ..   ...  ...       ...   ...       ...       ...    ...
 301     2     1   H     0  ...      2.96 -0.75      1.86      2.07   1.88
 302     0     2   A     0  ...      2.50 -0.25      2.03      1.90   2.02
 303     2     1   H     0  ...      2.34  0.50      1.97      1.96   1.97
 304     2     4   A     0  ...      2.52  0.25      2.04      1.89   2.03
 305     2     3   A     0  ...      2.97 -0.75      2.05      1.75   2.09

      PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0      NaN      NaN      NaN      NaN      NaN
 1      NaN      NaN      NaN      NaN      NaN
 2      NaN      NaN      NaN      NaN      NaN
 3      NaN      NaN      NaN      NaN      NaN
 4      NaN      NaN      NaN      NaN      NaN
 ..     ...      ...      ...      ...      ...
 301   2.06     1.99     2.08     1.88     2.00
 302   1.90     2.06     1.91     2.01     1.87
 303   1.95     1.98     1.98     1.92     1.95
 304   1.90     2.07     1.91     2.00     1.87
 305   1.83     2.13     1.89     2.04     1.83

 [1836 rows x 128 columns],
 'English Premier League':     Div             league_name  season        Date          HomeTeam  \
 0    E0  English Premier League      15  08/08/2015       Bournemouth
 1    E0  English Premier League      15  08/08/2015           Chelsea
 2    E0  English Premier League      15  08/08/2015           Everton
 3    E0  English Premier League      15  08/08/2015         Leicester
 4    E0  English Premier League      15  08/08/2015        Man United
 ..   ..                     ...     ...         ...               ...
 375  E0  English Premier League      20  23/05/2021         Liverpool
 376  E0  English Premier League      20  23/05/2021          Man City
 377  E0  English Premier League      20  23/05/2021  Sheffield United
 378  E0  English Premier League      20  23/05/2021          West Ham
 379  E0  English Premier League      20  23/05/2021            Wolves

            AwayTeam  FTHG  FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  \
 0       Aston Villa     0     1   A     0  ...       NaN   NaN      NaN
 1           Swansea     2     2   D     2  ...       NaN   NaN      NaN
 2           Watford     2     2   D     0  ...       NaN   NaN      NaN
 3        Sunderland     4     2   H     3  ...       NaN   NaN      NaN
 4         Tottenham     1     0   H     1  ...       NaN   NaN      NaN
 ..              ...   ...   ...  ..   ...  ...       ...   ...      ...
 375  Crystal Palace     2     0   H     1  ...      3.49 -2.25     1.86
 376         Everton     5     0   H     2  ...      2.77 -1.75     2.01
 377         Burnley     1     0   H     1  ...      2.05  0.00     2.04
 378     Southampton     3     0   H     2  ...      2.14 -0.75     2.00
 379      Man United     1     2   A     1  ...      1.62 -0.25     2.04

      B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 1         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 2         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 3         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 4         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 ..        ...    ...    ...      ...      ...      ...      ...
 375      2.04   1.88   2.03     1.98     2.14     1.88     2.00
 376      1.89   1.99   1.89     2.20     2.00     2.03     1.85
 377      1.86   2.05   1.86     2.17     1.90     2.03     1.84
 378      1.90   2.02   1.91     2.06     2.01     1.99     1.89
 379      1.86   2.10   1.84     2.10     1.94     2.00     1.88

 [2280 rows x 129 columns],
 'English League 1':     Div       league_name  season        Date            HomeTeam  \
 0    E2  English League 1      15    08/08/15              Burton
 1    E2  English League 1      15    08/08/15        Chesterfield
 2    E2  English League 1      15    08/08/15          Colchester
 3    E2  English League 1      15    08/08/15            Coventry
 4    E2  English League 1      15    08/08/15               Crewe
 ..   ..               ...     ...         ...                 ...
 547  E2  English League 1      20  09/05/2021  Milton Keynes Dons
 548  E2  English League 1      20  09/05/2021              Oxford
 549  E2  English League 1      20  09/05/2021          Portsmouth
 550  E2  English League 1      20  09/05/2021          Sunderland
 551  E2  English League 1      20  09/05/2021               Wigan

         AwayTeam  FTHG  FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  \
 0     Scunthorpe   2.0   1.0   H   0.0  ...       NaN   NaN      NaN
 1       Barnsley   3.0   1.0   H   0.0  ...       NaN   NaN      NaN
 2      Blackpool   2.0   2.0   D   1.0  ...       NaN   NaN      NaN
 3          Wigan   2.0   0.0   H   1.0  ...       NaN   NaN      NaN
 4      Port Vale   0.0   0.0   D   0.0  ...       NaN   NaN      NaN
 ..           ...   ...   ...  ..   ...  ...       ...   ...      ...
 547     Rochdale   0.0   3.0   A   0.0  ...      2.56 -0.75     1.88
 548       Burton   4.0   0.0   H   2.0  ...      2.38 -1.00     1.85
 549   Accrington   0.0   1.0   A   0.0  ...      2.21 -1.00     1.95
 550  Northampton   1.0   1.0   D   0.0  ...      2.13 -1.25     1.98
 551      Swindon   3.0   4.0   A   1.0  ...      2.28 -0.75     1.93

      B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 1         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 2         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 3         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 4         NaN    NaN    NaN      NaN      NaN      NaN      NaN
 ..        ...    ...    ...      ...      ...      ...      ...
 547      1.98   1.88   2.01     1.96     2.04     1.87     1.97
 548      2.00   1.88   2.02     2.11     2.06     1.88     1.95
 549      1.90   1.99   1.90     2.07     1.94     1.95     1.88
 550      1.88   2.02   1.88     2.10     1.91     2.01     1.83
 551      1.93   2.00   1.88     2.01     1.97     1.93     1.90

 [3161 rows x 129 columns],
 'English League 2':     Div       league_name  season        Date       HomeTeam        AwayTeam  \
 0    E3  English League 2      15    08/08/15     Accrington           Luton
 1    E3  English League 2      15    08/08/15  AFC Wimbledon        Plymouth
 2    E3  English League 2      15    08/08/15    Bristol Rvs     Northampton
 3    E3  English League 2      15    08/08/15      Cambridge  Newport County
 4    E3  English League 2      15    08/08/15         Exeter          Yeovil
 ..   ..               ...     ...         ...            ...             ...
 547  E3  English League 2      20  08/05/2021      Port Vale       Mansfield
 548  E3  English League 2      20  08/05/2021     Scunthorpe       Stevenage
 549  E3  English League 2      20  08/05/2021       Southend  Newport County
 550  E3  English League 2      20  08/05/2021       Tranmere      Colchester
 551  E3  English League 2      20  08/05/2021        Salford   Leyton Orient

      FTHG  FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  \
 0     1.0   1.0   D   0.0  ...       NaN   NaN      NaN       NaN    NaN
 1     0.0   2.0   A   0.0  ...       NaN   NaN      NaN       NaN    NaN
 2     0.0   1.0   A   0.0  ...       NaN   NaN      NaN       NaN    NaN
 3     3.0   0.0   H   1.0  ...       NaN   NaN      NaN       NaN    NaN
 4     3.0   2.0   H   2.0  ...       NaN   NaN      NaN       NaN    NaN
 ..    ...   ...  ..   ...  ...       ...   ...      ...       ...    ...
 547   0.0   3.0   A   0.0  ...      1.84  0.25     1.90      1.95   1.89
 548   0.0   1.0   A   0.0  ...      1.73  0.50     1.80      2.05   1.84
 549   1.0   1.0   D   1.0  ...      1.44  0.50     1.93      1.93   1.94
 550   0.0   0.0   D   0.0  ...      1.59 -0.75     2.05      1.80   2.05
 551   3.0   0.0   H   1.0  ...      1.87 -1.00     1.98      1.88   1.99

      PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0      NaN      NaN      NaN      NaN      NaN
 1      NaN      NaN      NaN      NaN      NaN
 2      NaN      NaN      NaN      NaN      NaN
 3      NaN      NaN      NaN      NaN      NaN
 4      NaN      NaN      NaN      NaN      NaN
 ..     ...      ...      ...      ...      ...
 547   2.00     1.95     2.07     1.85     1.97
 548   2.06     1.87     2.14     1.77     2.07
 549   1.94     1.97     1.97     1.91     1.91
 550   1.85     2.08     1.89     2.01     1.82
 551   1.90     2.01     1.96     1.96     1.86

 [3201 rows x 129 columns]}

In [23]:
dict_historical_data['English Premier League']

,Div,league_name,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,English Premier League,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,English Premier League,15,08/08/2015,Chelsea,Swansea,2,2,D,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,English Premier League,15,08/08/2015,Everton,Watford,2,2,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,English Premier League,15,08/08/2015,Leicester,Sunderland,4,2,H,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,English Premier League,15,08/08/2015,Man United,Tottenham,1,0,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,English Premier League,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,English Premier League,20,23/05/2021,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,English Premier League,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,English Premier League,20,23/05/2021,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,English Premier League,20,23/05/2021,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88